package discover

import (
	"fmt"
	"io"
	"os"
	"path/filepath"
	"time"
)

const yamlHeader = `# Generated by ` + "`dumpagent discover`" + ` %s (overwrite via --force)
# Top pick uncommented; alternates as comments below each source.
# Passwords NOT stored here. Set via env (<S>_DB_PASSWORD) or
` + "# `dumpagent set-secret <source>`. SYSDBA defaults to \"masterkey\" if" + `
# neither set; this is a Firebird stock default and emits a boot WARN.

`

// WriteYAML serializes 4 SourceResults into the canonical YAML format
// with top picks uncommented and alternates as inline comments.
func WriteYAML(w io.Writer, results []SourceResult) error {
	if _, err := fmt.Fprintf(w, yamlHeader, time.Now().UTC().Format(time.RFC3339)); err != nil {
		return err
	}
	bySrc := indexBySource(results)
	for _, src := range []SourceID{SourceCNES, SourceSIHD, SourceBPA, SourceSIA} {
		if err := writeOneSource(w, src, bySrc[src]); err != nil {
			return err
		}
	}
	return nil
}

func indexBySource(results []SourceResult) map[SourceID]SourceResult {
	out := map[SourceID]SourceResult{}
	for _, r := range results {
		out[r.Source] = r
	}
	return out
}

func writeOneSource(w io.Writer, src SourceID, r SourceResult) error {
	if src == SourceSIA {
		return writeSIABlock(w, r)
	}
	return writeFBBlock(w, src, r)
}

func writeFBBlock(w io.Writer, src SourceID, r SourceResult) error {
	path := r.Top.Path
	if _, err := fmt.Fprintf(w, "%s:\n", src.String()); err != nil {
		return err
	}
	if _, err := fmt.Fprintf(w, "  host: localhost\n"); err != nil {
		return err
	}
	if _, err := fmt.Fprintf(w, "  port: 3050\n"); err != nil {
		return err
	}
	if _, err := fmt.Fprintf(w, "  database_path: %s\n", path); err != nil {
		return err
	}
	if _, err := fmt.Fprintf(w, "  user: SYSDBA\n"); err != nil {
		return err
	}
	if _, err := fmt.Fprintf(w, "  charset: WIN1252\n"); err != nil {
		return err
	}
	writeAlternateComments(w, r)
	if path == "" {
		fmt.Fprintf(w, "  # (no candidates found; set database_path manually or via env %s_DB_PATH)\n",
			upperSource(src))
	}
	fmt.Fprintln(w)
	return nil
}

func writeSIABlock(w io.Writer, r SourceResult) error {
	if _, err := fmt.Fprintf(w, "sia:\n"); err != nil {
		return err
	}
	if _, err := fmt.Fprintf(w, "  dbf_dir: %s\n", r.Top.Path); err != nil {
		return err
	}
	writeAlternateComments(w, r)
	if r.Top.Path == "" {
		fmt.Fprintf(w, "  # (no candidates found; set dbf_dir manually or via env SIA_DIR)\n")
	}
	fmt.Fprintln(w)
	return nil
}

func writeAlternateComments(w io.Writer, r SourceResult) {
	if r.Top.Path != "" {
		fmt.Fprintf(w, "  # candidate strategy=%-12s score=%d path=%s\n",
			r.Top.Strategy.String(), r.Top.Score, r.Top.Path)
	}
	for _, a := range r.Alternates {
		fmt.Fprintf(w, "  # candidate strategy=%-12s score=%d path=%s\n",
			a.Strategy.String(), a.Score, a.Path)
	}
}

func upperSource(s SourceID) string {
	switch s {
	case SourceCNES:
		return "CNES"
	case SourceSIHD:
		return "SIHD"
	case SourceBPA:
		return "BPA"
	default:
		return ""
	}
}

// WriteYAMLAtomic writes via .tmp + os.Rename to avoid half-written files.
func WriteYAMLAtomic(path string, results []SourceResult) error {
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return err
	}
	tmp := path + ".tmp"
	f, err := os.OpenFile(tmp, os.O_WRONLY|os.O_CREATE|os.O_TRUNC, 0o644)
	if err != nil {
		return err
	}
	if err := WriteYAML(f, results); err != nil {
		f.Close()
		os.Remove(tmp)
		return err
	}
	if err := f.Close(); err != nil {
		os.Remove(tmp)
		return err
	}
	return os.Rename(tmp, path)
}
