#!/usr/bin/env bash
# One-time, idempotent provisioning of the develop staging stack on the VPS.
# Run as root on the target host:
#
#   CI_PUBLIC_KEY="ssh-ed25519 AAAA... cnesdata-dev-ci" \
#     bash bootstrap.sh
#
# GHCR_USER/GHCR_PAT are optional: only needed if the ghcr.io/viniclus/cnesdata/*
# packages are private. Prefer making them public after the first push instead
# of retaining a PAT on the VPS.
#
# Safe to re-run: every step checks current state before mutating it.
set -euo pipefail

: "${CI_PUBLIC_KEY:?set CI_PUBLIC_KEY to the deploy CI public SSH key}"
GHCR_USER="${GHCR_USER:-}"
GHCR_PAT="${GHCR_PAT:-}"

STACK_DIR=/opt/cnesdata-dev
DEPLOY_USER=cnesdeploy
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

echo "==> deploy user"
if ! id "$DEPLOY_USER" &>/dev/null; then
  useradd -m -s /bin/bash -G docker "$DEPLOY_USER"
fi

echo "==> stack directory"
mkdir -p "$STACK_DIR"/{secrets,keycloak}
chown -R "$DEPLOY_USER:$DEPLOY_USER" "$STACK_DIR"
# 755: containers run as their own non-root UID and need to traverse this
# dir and read the dev CA below (bind mount does not remap ownership).
chmod 755 "$STACK_DIR/secrets"

echo "==> forced-command SSH key"
install -d -m 700 -o "$DEPLOY_USER" -g "$DEPLOY_USER" "/home/$DEPLOY_USER/.ssh"
AUTH_KEYS="/home/$DEPLOY_USER/.ssh/authorized_keys"
RESTRICTED_KEY="command=\"/usr/local/bin/cnesdata-dev-deploy\",no-port-forwarding,no-agent-forwarding,no-X11-forwarding,no-pty $CI_PUBLIC_KEY"
touch "$AUTH_KEYS"
grep -qF "$CI_PUBLIC_KEY" "$AUTH_KEYS" || echo "$RESTRICTED_KEY" >> "$AUTH_KEYS"
chmod 600 "$AUTH_KEYS"
chown "$DEPLOY_USER:$DEPLOY_USER" "$AUTH_KEYS"

echo "==> deploy.sh"
install -m 755 -o root -g root "$SCRIPT_DIR/deploy.sh" /usr/local/bin/cnesdata-dev-deploy
touch /var/log/cnesdata-dev-deploy.log
chown "$DEPLOY_USER:$DEPLOY_USER" /var/log/cnesdata-dev-deploy.log

echo "==> compose file"
install -m 644 -o "$DEPLOY_USER" -g "$DEPLOY_USER" \
  "$SCRIPT_DIR/docker-compose.dev.yml" "$STACK_DIR/docker-compose.dev.yml"

echo "==> shared edge network"
docker network inspect cnesdata_edge &>/dev/null || docker network create cnesdata_edge

echo "==> .env (secrets generated once, never overwritten)"
ENV_FILE="$STACK_DIR/.env"
if [ ! -f "$ENV_FILE" ]; then
  PG_PASS="$(openssl rand -base64 24)"
  MINIO_PASS="$(openssl rand -base64 24)"
  KC_PASS="$(openssl rand -base64 24)"
  cat > "$ENV_FILE" <<EOF
# Generated by bootstrap.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ). Do not commit.
POSTGRES_USER=cnesdata
POSTGRES_PASSWORD=$PG_PASS
POSTGRES_DB=cnesdata
DB_URL=postgresql+psycopg://cnesdata:$PG_PASS@postgres:5432/cnesdata

# App services reuse these as their S3 credentials (S3_ENDPOINT_URL is
# hardcoded to http://minio:9000 in docker-compose.dev.yml). AIStor Free
# also needs a license file at secrets/minio.license — this script does NOT
# create it; place one manually (see docs/development.md#object-storage-license).
MINIO_ROOT_USER=cnesdata-dev
MINIO_ROOT_PASSWORD=$MINIO_PASS
S3_BUCKET=cnesdata-landing-dev

KEYCLOAK_ADMIN=admin
KEYCLOAK_ADMIN_PASSWORD=$KC_PASS

PUBLIC_DOMAIN=dev.cnesdata.vinisantana.com
DASHBOARD_OIDC_ISSUER=https://dev.cnesdata.vinisantana.com/idp/realms/cnesdata
DASHBOARD_OIDC_AUDIENCE=cnesdata-dashboard
AUTH_DEVICE_VERIFICATION_URI=https://dev.cnesdata.vinisantana.com/activate
AUTH_REQUIRED=required

COD_MUN_IBGE=354130
ID_MUNICIPIO_IBGE7=3541308
CNPJ_MANTENEDORA=55293427000117
COMPETENCIA_ANO=2026
COMPETENCIA_MES=1

PROCESSOR_POLL_INTERVAL=5.0
PROCESSOR_IDLE_POLL_INTERVAL=60.0
EOF
  chmod 600 "$ENV_FILE"
  chown "$DEPLOY_USER:$DEPLOY_USER" "$ENV_FILE"
  echo "    generated new .env with fresh random secrets"
else
  echo "    .env already exists, left untouched"
fi

echo "==> dev CA (independent from production CA)"
CA_CRT="$STACK_DIR/secrets/ca.crt"
CA_KEY="$STACK_DIR/secrets/ca.key"
if [ ! -f "$CA_CRT" ] || [ ! -f "$CA_KEY" ]; then
  openssl req -x509 -newkey rsa:4096 -sha256 -days 3650 -nodes \
    -keyout "$CA_KEY" -out "$CA_CRT" \
    -subj "/O=CnesData Dev/CN=cnesdata-dev-ca"
  chmod 644 "$CA_KEY" "$CA_CRT"
  chown "$DEPLOY_USER:$DEPLOY_USER" "$CA_KEY" "$CA_CRT"
  echo "    generated new dev CA"
else
  echo "    dev CA already exists, left untouched"
fi

echo "==> Keycloak dev realm (redirect URIs rewritten for dev.* host)"
REPO_REALM="$(cd "$SCRIPT_DIR/../.." && pwd)/docker-compose.keycloak/realm.json"
if [ -f "$REPO_REALM" ]; then
  sed 's#http://localhost:5173#https://dev.cnesdata.vinisantana.com#g' \
    "$REPO_REALM" > "$STACK_DIR/keycloak/realm.json"
  chown "$DEPLOY_USER:$DEPLOY_USER" "$STACK_DIR/keycloak/realm.json"
else
  echo "    WARNING: $REPO_REALM not found, keycloak/realm.json not written"
fi

if [ -n "$GHCR_PAT" ] && [ -n "$GHCR_USER" ]; then
  echo "==> GHCR login (read-only pull, as $DEPLOY_USER)"
  su - "$DEPLOY_USER" -c "echo '$GHCR_PAT' | docker login ghcr.io -u '$GHCR_USER' --password-stdin"
else
  echo "==> GHCR login skipped (GHCR_USER/GHCR_PAT not set)"
  echo "    packages must be public, or run 'docker login ghcr.io' manually as $DEPLOY_USER"
fi

echo "==> done. First deploy: ssh -i <ci-key> $DEPLOY_USER@<host> develop-<sha>"
