// Package apiclient provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package apiclient

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"
	"time"

	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for RegisterRequestFonteSistema.
const (
	BPAC         RegisterRequestFonteSistema = "BPA_C"
	BPAI         RegisterRequestFonteSistema = "BPA_I"
	CNESLOCAL    RegisterRequestFonteSistema = "CNES_LOCAL"
	CNESNACIONAL RegisterRequestFonteSistema = "CNES_NACIONAL"
	SIAAPA       RegisterRequestFonteSistema = "SIA_APA"
	SIABPI       RegisterRequestFonteSistema = "SIA_BPI"
	SIHD         RegisterRequestFonteSistema = "SIHD"
)

// AgentStatusResponse defines model for AgentStatusResponse.
type AgentStatusResponse struct {
	AgentVersion    *string `json:"agent_version"`
	JobsCompleted7d int     `json:"jobs_completed_7d"`
	JobsFailed7d    int     `json:"jobs_failed_7d"`
	LastSeen        *string `json:"last_seen"`
	MachineId       *string `json:"machine_id"`
	TenantId        string  `json:"tenant_id"`
}

// CompletePayload defines model for CompletePayload.
type CompletePayload struct {
	RowCount int    `json:"row_count"`
	Sha256   string `json:"sha256"`
}

// FailPayload defines model for FailPayload.
type FailPayload struct {
	Error string `json:"error"`
}

// HTTPValidationError defines model for HTTPValidationError.
type HTTPValidationError struct {
	Detail *[]ValidationError `json:"detail,omitempty"`
}

// HealthResponse defines model for HealthResponse.
type HealthResponse struct {
	DbConnected bool      `json:"db_connected"`
	Status      string    `json:"status"`
	Timestamp   time.Time `json:"timestamp"`
}

// RegisterRequest defines model for RegisterRequest.
type RegisterRequest struct {
	AgentVersion string                      `json:"agent_version"`
	Competencia  int                         `json:"competencia"`
	FonteSistema RegisterRequestFonteSistema `json:"fonte_sistema"`
	JobId        openapi_types.UUID          `json:"job_id"`
	MachineId    string                      `json:"machine_id"`
	TenantId     string                      `json:"tenant_id"`
	TipoExtracao string                      `json:"tipo_extracao"`
}

// RegisterRequestFonteSistema defines model for RegisterRequest.FonteSistema.
type RegisterRequestFonteSistema string

// RegisterResponse defines model for RegisterResponse.
type RegisterResponse struct {
	ExtractionId openapi_types.UUID `json:"extraction_id"`
	UploadUrl    string             `json:"upload_url"`
}

// Defines values for FileManifestFatoSubtype.
const (
	FatoCNESVinculo     FileManifestFatoSubtype = "CNES_VINCULO"
	FatoSIHDInternacao  FileManifestFatoSubtype = "SIHD_INTERNACAO"
	FatoSIHDProcAIH     FileManifestFatoSubtype = "SIHD_PROC_AIH"
	FatoBPAC            FileManifestFatoSubtype = "BPA_C"
	FatoBPAI            FileManifestFatoSubtype = "BPA_I"
	FatoSIAAPA          FileManifestFatoSubtype = "SIA_APA"
	FatoSIABPI          FileManifestFatoSubtype = "SIA_BPI"
	FatoSIABPIHST       FileManifestFatoSubtype = "SIA_BPIHST"
	FatoDIMSigtap       FileManifestFatoSubtype = "DIM_SIGTAP"
	FatoDIMMunicipio    FileManifestFatoSubtype = "DIM_MUNICIPIO"
)

// FileManifestFatoSubtype defines model for FileManifest.FatoSubtype.
type FileManifestFatoSubtype string

// FileManifest defines model for FileManifest.
type FileManifest struct {
	MinioKey    string                  `json:"minio_key"`
	FatoSubtype FileManifestFatoSubtype `json:"fato_subtype"`
	SizeBytes   int64                   `json:"size_bytes"`
	Sha256      string                  `json:"sha256"`
}

// JobRegisterRequest defines model for JobRegisterRequest.
type JobRegisterRequest struct {
	JobId openapi_types.UUID `json:"job_id"`
	Files []FileManifest     `json:"files"`
}

// JobRegisterResponse defines model for JobRegisterResponse.
type JobRegisterResponse struct {
	JobId  string `json:"job_id"`
	Status string `json:"status"`
}

// ValidationError defines model for ValidationError.
type ValidationError struct {
	Ctx   *map[string]interface{}    `json:"ctx,omitempty"`
	Input *interface{}               `json:"input,omitempty"`
	Loc   []ValidationError_Loc_Item `json:"loc"`
	Msg   string                     `json:"msg"`
	Type  string                     `json:"type"`
}

// ValidationErrorLoc0 defines model for .
type ValidationErrorLoc0 = string

// ValidationErrorLoc1 defines model for .
type ValidationErrorLoc1 = int

// ValidationError_Loc_Item defines model for ValidationError.loc.Item.
type ValidationError_Loc_Item struct {
	union json.RawMessage
}

// GetAgentStatusApiV1AgentsStatusGetParams defines parameters for GetAgentStatusApiV1AgentsStatusGet.
type GetAgentStatusApiV1AgentsStatusGetParams struct {
	TenantId  string `form:"tenant_id" json:"tenant_id"`
	XTenantId string `json:"X-Tenant-Id"`
}

// NextExtractionApiV1JobsNextGetParams defines parameters for NextExtractionApiV1JobsNextGet.
type NextExtractionApiV1JobsNextGetParams struct {
	ProcessorId string `form:"processor_id" json:"processor_id"`
	LeaseSecs   *int   `form:"lease_secs,omitempty" json:"lease_secs,omitempty"`
}

// HeartbeatExtractionApiV1JobsExtractionIdHeartbeatPostParams defines parameters for HeartbeatExtractionApiV1JobsExtractionIdHeartbeatPost.
type HeartbeatExtractionApiV1JobsExtractionIdHeartbeatPostParams struct {
	ProcessorId string `form:"processor_id" json:"processor_id"`
}

// RegisterExtractionApiV1JobsRegisterPostJSONRequestBody defines body for RegisterExtractionApiV1JobsRegisterPost for application/json ContentType.
type RegisterExtractionApiV1JobsRegisterPostJSONRequestBody = RegisterRequest

// CompleteExtractionApiV1JobsExtractionIdCompletePostJSONRequestBody defines body for CompleteExtractionApiV1JobsExtractionIdCompletePost for application/json ContentType.
type CompleteExtractionApiV1JobsExtractionIdCompletePostJSONRequestBody = CompletePayload

// FailExtractionApiV1JobsExtractionIdFailPostJSONRequestBody defines body for FailExtractionApiV1JobsExtractionIdFailPost for application/json ContentType.
type FailExtractionApiV1JobsExtractionIdFailPostJSONRequestBody = FailPayload

// AsValidationErrorLoc0 returns the union data inside the ValidationError_Loc_Item as a ValidationErrorLoc0
func (t ValidationError_Loc_Item) AsValidationErrorLoc0() (ValidationErrorLoc0, error) {
	var body ValidationErrorLoc0
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromValidationErrorLoc0 overwrites any union data inside the ValidationError_Loc_Item as the provided ValidationErrorLoc0
func (t *ValidationError_Loc_Item) FromValidationErrorLoc0(v ValidationErrorLoc0) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeValidationErrorLoc0 performs a merge with any union data inside the ValidationError_Loc_Item, using the provided ValidationErrorLoc0
func (t *ValidationError_Loc_Item) MergeValidationErrorLoc0(v ValidationErrorLoc0) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsValidationErrorLoc1 returns the union data inside the ValidationError_Loc_Item as a ValidationErrorLoc1
func (t ValidationError_Loc_Item) AsValidationErrorLoc1() (ValidationErrorLoc1, error) {
	var body ValidationErrorLoc1
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromValidationErrorLoc1 overwrites any union data inside the ValidationError_Loc_Item as the provided ValidationErrorLoc1
func (t *ValidationError_Loc_Item) FromValidationErrorLoc1(v ValidationErrorLoc1) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeValidationErrorLoc1 performs a merge with any union data inside the ValidationError_Loc_Item, using the provided ValidationErrorLoc1
func (t *ValidationError_Loc_Item) MergeValidationErrorLoc1(v ValidationErrorLoc1) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t ValidationError_Loc_Item) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *ValidationError_Loc_Item) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// ReapLeasesApiV1AdminReapLeasesPost request
	ReapLeasesApiV1AdminReapLeasesPost(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetAgentStatusApiV1AgentsStatusGet request
	GetAgentStatusApiV1AgentsStatusGet(ctx context.Context, params *GetAgentStatusApiV1AgentsStatusGetParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// NextExtractionApiV1JobsNextGet request
	NextExtractionApiV1JobsNextGet(ctx context.Context, params *NextExtractionApiV1JobsNextGetParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// RegisterExtractionApiV1JobsRegisterPostWithBody request with any body
	RegisterExtractionApiV1JobsRegisterPostWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	RegisterExtractionApiV1JobsRegisterPost(ctx context.Context, body RegisterExtractionApiV1JobsRegisterPostJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// CompleteExtractionApiV1JobsExtractionIdCompletePostWithBody request with any body
	CompleteExtractionApiV1JobsExtractionIdCompletePostWithBody(ctx context.Context, extractionId openapi_types.UUID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	CompleteExtractionApiV1JobsExtractionIdCompletePost(ctx context.Context, extractionId openapi_types.UUID, body CompleteExtractionApiV1JobsExtractionIdCompletePostJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// FailExtractionApiV1JobsExtractionIdFailPostWithBody request with any body
	FailExtractionApiV1JobsExtractionIdFailPostWithBody(ctx context.Context, extractionId openapi_types.UUID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	FailExtractionApiV1JobsExtractionIdFailPost(ctx context.Context, extractionId openapi_types.UUID, body FailExtractionApiV1JobsExtractionIdFailPostJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// HeartbeatExtractionApiV1JobsExtractionIdHeartbeatPost request
	HeartbeatExtractionApiV1JobsExtractionIdHeartbeatPost(ctx context.Context, extractionId openapi_types.UUID, params *HeartbeatExtractionApiV1JobsExtractionIdHeartbeatPostParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// HealthCheckApiV1SystemHealthGet request
	HealthCheckApiV1SystemHealthGet(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) ReapLeasesApiV1AdminReapLeasesPost(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewReapLeasesApiV1AdminReapLeasesPostRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetAgentStatusApiV1AgentsStatusGet(ctx context.Context, params *GetAgentStatusApiV1AgentsStatusGetParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetAgentStatusApiV1AgentsStatusGetRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) NextExtractionApiV1JobsNextGet(ctx context.Context, params *NextExtractionApiV1JobsNextGetParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewNextExtractionApiV1JobsNextGetRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) RegisterExtractionApiV1JobsRegisterPostWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewRegisterExtractionApiV1JobsRegisterPostRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) RegisterExtractionApiV1JobsRegisterPost(ctx context.Context, body RegisterExtractionApiV1JobsRegisterPostJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewRegisterExtractionApiV1JobsRegisterPostRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CompleteExtractionApiV1JobsExtractionIdCompletePostWithBody(ctx context.Context, extractionId openapi_types.UUID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCompleteExtractionApiV1JobsExtractionIdCompletePostRequestWithBody(c.Server, extractionId, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CompleteExtractionApiV1JobsExtractionIdCompletePost(ctx context.Context, extractionId openapi_types.UUID, body CompleteExtractionApiV1JobsExtractionIdCompletePostJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCompleteExtractionApiV1JobsExtractionIdCompletePostRequest(c.Server, extractionId, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) FailExtractionApiV1JobsExtractionIdFailPostWithBody(ctx context.Context, extractionId openapi_types.UUID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewFailExtractionApiV1JobsExtractionIdFailPostRequestWithBody(c.Server, extractionId, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) FailExtractionApiV1JobsExtractionIdFailPost(ctx context.Context, extractionId openapi_types.UUID, body FailExtractionApiV1JobsExtractionIdFailPostJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewFailExtractionApiV1JobsExtractionIdFailPostRequest(c.Server, extractionId, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) HeartbeatExtractionApiV1JobsExtractionIdHeartbeatPost(ctx context.Context, extractionId openapi_types.UUID, params *HeartbeatExtractionApiV1JobsExtractionIdHeartbeatPostParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewHeartbeatExtractionApiV1JobsExtractionIdHeartbeatPostRequest(c.Server, extractionId, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) HealthCheckApiV1SystemHealthGet(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewHealthCheckApiV1SystemHealthGetRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewReapLeasesApiV1AdminReapLeasesPostRequest generates requests for ReapLeasesApiV1AdminReapLeasesPost
func NewReapLeasesApiV1AdminReapLeasesPostRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/admin/reap-leases")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetAgentStatusApiV1AgentsStatusGetRequest generates requests for GetAgentStatusApiV1AgentsStatusGet
func NewGetAgentStatusApiV1AgentsStatusGetRequest(server string, params *GetAgentStatusApiV1AgentsStatusGetParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/agents/status")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if queryFrag, err := runtime.StyleParamWithLocation("form", true, "tenant_id", runtime.ParamLocationQuery, params.TenantId); err != nil {
			return nil, err
		} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
			return nil, err
		} else {
			for k, v := range parsed {
				for _, v2 := range v {
					queryValues.Add(k, v2)
				}
			}
		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	if params != nil {

		var headerParam0 string

		headerParam0, err = runtime.StyleParamWithLocation("simple", false, "X-Tenant-Id", runtime.ParamLocationHeader, params.XTenantId)
		if err != nil {
			return nil, err
		}

		req.Header.Set("X-Tenant-Id", headerParam0)

	}

	return req, nil
}

// NewNextExtractionApiV1JobsNextGetRequest generates requests for NextExtractionApiV1JobsNextGet
func NewNextExtractionApiV1JobsNextGetRequest(server string, params *NextExtractionApiV1JobsNextGetParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/jobs/next")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if queryFrag, err := runtime.StyleParamWithLocation("form", true, "processor_id", runtime.ParamLocationQuery, params.ProcessorId); err != nil {
			return nil, err
		} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
			return nil, err
		} else {
			for k, v := range parsed {
				for _, v2 := range v {
					queryValues.Add(k, v2)
				}
			}
		}

		if params.LeaseSecs != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "lease_secs", runtime.ParamLocationQuery, *params.LeaseSecs); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewRegisterExtractionApiV1JobsRegisterPostRequest calls the generic RegisterExtractionApiV1JobsRegisterPost builder with application/json body
func NewRegisterExtractionApiV1JobsRegisterPostRequest(server string, body RegisterExtractionApiV1JobsRegisterPostJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewRegisterExtractionApiV1JobsRegisterPostRequestWithBody(server, "application/json", bodyReader)
}

// NewRegisterExtractionApiV1JobsRegisterPostRequestWithBody generates requests for RegisterExtractionApiV1JobsRegisterPost with any type of body
func NewRegisterExtractionApiV1JobsRegisterPostRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/jobs/register")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewCompleteExtractionApiV1JobsExtractionIdCompletePostRequest calls the generic CompleteExtractionApiV1JobsExtractionIdCompletePost builder with application/json body
func NewCompleteExtractionApiV1JobsExtractionIdCompletePostRequest(server string, extractionId openapi_types.UUID, body CompleteExtractionApiV1JobsExtractionIdCompletePostJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewCompleteExtractionApiV1JobsExtractionIdCompletePostRequestWithBody(server, extractionId, "application/json", bodyReader)
}

// NewCompleteExtractionApiV1JobsExtractionIdCompletePostRequestWithBody generates requests for CompleteExtractionApiV1JobsExtractionIdCompletePost with any type of body
func NewCompleteExtractionApiV1JobsExtractionIdCompletePostRequestWithBody(server string, extractionId openapi_types.UUID, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "extraction_id", runtime.ParamLocationPath, extractionId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/jobs/%s/complete", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewFailExtractionApiV1JobsExtractionIdFailPostRequest calls the generic FailExtractionApiV1JobsExtractionIdFailPost builder with application/json body
func NewFailExtractionApiV1JobsExtractionIdFailPostRequest(server string, extractionId openapi_types.UUID, body FailExtractionApiV1JobsExtractionIdFailPostJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewFailExtractionApiV1JobsExtractionIdFailPostRequestWithBody(server, extractionId, "application/json", bodyReader)
}

// NewFailExtractionApiV1JobsExtractionIdFailPostRequestWithBody generates requests for FailExtractionApiV1JobsExtractionIdFailPost with any type of body
func NewFailExtractionApiV1JobsExtractionIdFailPostRequestWithBody(server string, extractionId openapi_types.UUID, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "extraction_id", runtime.ParamLocationPath, extractionId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/jobs/%s/fail", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewHeartbeatExtractionApiV1JobsExtractionIdHeartbeatPostRequest generates requests for HeartbeatExtractionApiV1JobsExtractionIdHeartbeatPost
func NewHeartbeatExtractionApiV1JobsExtractionIdHeartbeatPostRequest(server string, extractionId openapi_types.UUID, params *HeartbeatExtractionApiV1JobsExtractionIdHeartbeatPostParams) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "extraction_id", runtime.ParamLocationPath, extractionId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/jobs/%s/heartbeat", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if queryFrag, err := runtime.StyleParamWithLocation("form", true, "processor_id", runtime.ParamLocationQuery, params.ProcessorId); err != nil {
			return nil, err
		} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
			return nil, err
		} else {
			for k, v := range parsed {
				for _, v2 := range v {
					queryValues.Add(k, v2)
				}
			}
		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("POST", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewHealthCheckApiV1SystemHealthGetRequest generates requests for HealthCheckApiV1SystemHealthGet
func NewHealthCheckApiV1SystemHealthGetRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/system/health")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// ReapLeasesApiV1AdminReapLeasesPostWithResponse request
	ReapLeasesApiV1AdminReapLeasesPostWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*ReapLeasesApiV1AdminReapLeasesPostResponse, error)

	// GetAgentStatusApiV1AgentsStatusGetWithResponse request
	GetAgentStatusApiV1AgentsStatusGetWithResponse(ctx context.Context, params *GetAgentStatusApiV1AgentsStatusGetParams, reqEditors ...RequestEditorFn) (*GetAgentStatusApiV1AgentsStatusGetResponse, error)

	// NextExtractionApiV1JobsNextGetWithResponse request
	NextExtractionApiV1JobsNextGetWithResponse(ctx context.Context, params *NextExtractionApiV1JobsNextGetParams, reqEditors ...RequestEditorFn) (*NextExtractionApiV1JobsNextGetResponse, error)

	// RegisterExtractionApiV1JobsRegisterPostWithBodyWithResponse request with any body
	RegisterExtractionApiV1JobsRegisterPostWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*RegisterExtractionApiV1JobsRegisterPostResponse, error)

	RegisterExtractionApiV1JobsRegisterPostWithResponse(ctx context.Context, body RegisterExtractionApiV1JobsRegisterPostJSONRequestBody, reqEditors ...RequestEditorFn) (*RegisterExtractionApiV1JobsRegisterPostResponse, error)

	// CompleteExtractionApiV1JobsExtractionIdCompletePostWithBodyWithResponse request with any body
	CompleteExtractionApiV1JobsExtractionIdCompletePostWithBodyWithResponse(ctx context.Context, extractionId openapi_types.UUID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CompleteExtractionApiV1JobsExtractionIdCompletePostResponse, error)

	CompleteExtractionApiV1JobsExtractionIdCompletePostWithResponse(ctx context.Context, extractionId openapi_types.UUID, body CompleteExtractionApiV1JobsExtractionIdCompletePostJSONRequestBody, reqEditors ...RequestEditorFn) (*CompleteExtractionApiV1JobsExtractionIdCompletePostResponse, error)

	// FailExtractionApiV1JobsExtractionIdFailPostWithBodyWithResponse request with any body
	FailExtractionApiV1JobsExtractionIdFailPostWithBodyWithResponse(ctx context.Context, extractionId openapi_types.UUID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*FailExtractionApiV1JobsExtractionIdFailPostResponse, error)

	FailExtractionApiV1JobsExtractionIdFailPostWithResponse(ctx context.Context, extractionId openapi_types.UUID, body FailExtractionApiV1JobsExtractionIdFailPostJSONRequestBody, reqEditors ...RequestEditorFn) (*FailExtractionApiV1JobsExtractionIdFailPostResponse, error)

	// HeartbeatExtractionApiV1JobsExtractionIdHeartbeatPostWithResponse request
	HeartbeatExtractionApiV1JobsExtractionIdHeartbeatPostWithResponse(ctx context.Context, extractionId openapi_types.UUID, params *HeartbeatExtractionApiV1JobsExtractionIdHeartbeatPostParams, reqEditors ...RequestEditorFn) (*HeartbeatExtractionApiV1JobsExtractionIdHeartbeatPostResponse, error)

	// HealthCheckApiV1SystemHealthGetWithResponse request
	HealthCheckApiV1SystemHealthGetWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*HealthCheckApiV1SystemHealthGetResponse, error)
}

type ReapLeasesApiV1AdminReapLeasesPostResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *map[string]interface{}
}

// Status returns HTTPResponse.Status
func (r ReapLeasesApiV1AdminReapLeasesPostResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ReapLeasesApiV1AdminReapLeasesPostResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetAgentStatusApiV1AgentsStatusGetResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *AgentStatusResponse
	JSON422      *HTTPValidationError
}

// Status returns HTTPResponse.Status
func (r GetAgentStatusApiV1AgentsStatusGetResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetAgentStatusApiV1AgentsStatusGetResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type NextExtractionApiV1JobsNextGetResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *map[string]interface{}
	JSON422      *HTTPValidationError
}

// Status returns HTTPResponse.Status
func (r NextExtractionApiV1JobsNextGetResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r NextExtractionApiV1JobsNextGetResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type RegisterExtractionApiV1JobsRegisterPostResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON201      *RegisterResponse
	JSON422      *HTTPValidationError
}

// Status returns HTTPResponse.Status
func (r RegisterExtractionApiV1JobsRegisterPostResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r RegisterExtractionApiV1JobsRegisterPostResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type CompleteExtractionApiV1JobsExtractionIdCompletePostResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *map[string]interface{}
	JSON422      *HTTPValidationError
}

// Status returns HTTPResponse.Status
func (r CompleteExtractionApiV1JobsExtractionIdCompletePostResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r CompleteExtractionApiV1JobsExtractionIdCompletePostResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type FailExtractionApiV1JobsExtractionIdFailPostResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *map[string]interface{}
	JSON422      *HTTPValidationError
}

// Status returns HTTPResponse.Status
func (r FailExtractionApiV1JobsExtractionIdFailPostResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r FailExtractionApiV1JobsExtractionIdFailPostResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type HeartbeatExtractionApiV1JobsExtractionIdHeartbeatPostResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *map[string]interface{}
	JSON422      *HTTPValidationError
}

// Status returns HTTPResponse.Status
func (r HeartbeatExtractionApiV1JobsExtractionIdHeartbeatPostResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r HeartbeatExtractionApiV1JobsExtractionIdHeartbeatPostResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type HealthCheckApiV1SystemHealthGetResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *HealthResponse
}

// Status returns HTTPResponse.Status
func (r HealthCheckApiV1SystemHealthGetResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r HealthCheckApiV1SystemHealthGetResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// PostJobsRegisterResponse resposta do POST /api/v1/jobs/register (N-file manifest).
type PostJobsRegisterResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *JobRegisterResponse
	JSON422      *HTTPValidationError
}

// Status returns HTTPResponse.Status.
func (r PostJobsRegisterResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode.
func (r PostJobsRegisterResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ReapLeasesApiV1AdminReapLeasesPostWithResponse request returning *ReapLeasesApiV1AdminReapLeasesPostResponse
func (c *ClientWithResponses) ReapLeasesApiV1AdminReapLeasesPostWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*ReapLeasesApiV1AdminReapLeasesPostResponse, error) {
	rsp, err := c.ReapLeasesApiV1AdminReapLeasesPost(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseReapLeasesApiV1AdminReapLeasesPostResponse(rsp)
}

// GetAgentStatusApiV1AgentsStatusGetWithResponse request returning *GetAgentStatusApiV1AgentsStatusGetResponse
func (c *ClientWithResponses) GetAgentStatusApiV1AgentsStatusGetWithResponse(ctx context.Context, params *GetAgentStatusApiV1AgentsStatusGetParams, reqEditors ...RequestEditorFn) (*GetAgentStatusApiV1AgentsStatusGetResponse, error) {
	rsp, err := c.GetAgentStatusApiV1AgentsStatusGet(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetAgentStatusApiV1AgentsStatusGetResponse(rsp)
}

// NextExtractionApiV1JobsNextGetWithResponse request returning *NextExtractionApiV1JobsNextGetResponse
func (c *ClientWithResponses) NextExtractionApiV1JobsNextGetWithResponse(ctx context.Context, params *NextExtractionApiV1JobsNextGetParams, reqEditors ...RequestEditorFn) (*NextExtractionApiV1JobsNextGetResponse, error) {
	rsp, err := c.NextExtractionApiV1JobsNextGet(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseNextExtractionApiV1JobsNextGetResponse(rsp)
}

// RegisterExtractionApiV1JobsRegisterPostWithBodyWithResponse request with arbitrary body returning *RegisterExtractionApiV1JobsRegisterPostResponse
func (c *ClientWithResponses) RegisterExtractionApiV1JobsRegisterPostWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*RegisterExtractionApiV1JobsRegisterPostResponse, error) {
	rsp, err := c.RegisterExtractionApiV1JobsRegisterPostWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseRegisterExtractionApiV1JobsRegisterPostResponse(rsp)
}

func (c *ClientWithResponses) RegisterExtractionApiV1JobsRegisterPostWithResponse(ctx context.Context, body RegisterExtractionApiV1JobsRegisterPostJSONRequestBody, reqEditors ...RequestEditorFn) (*RegisterExtractionApiV1JobsRegisterPostResponse, error) {
	rsp, err := c.RegisterExtractionApiV1JobsRegisterPost(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseRegisterExtractionApiV1JobsRegisterPostResponse(rsp)
}

// CompleteExtractionApiV1JobsExtractionIdCompletePostWithBodyWithResponse request with arbitrary body returning *CompleteExtractionApiV1JobsExtractionIdCompletePostResponse
func (c *ClientWithResponses) CompleteExtractionApiV1JobsExtractionIdCompletePostWithBodyWithResponse(ctx context.Context, extractionId openapi_types.UUID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CompleteExtractionApiV1JobsExtractionIdCompletePostResponse, error) {
	rsp, err := c.CompleteExtractionApiV1JobsExtractionIdCompletePostWithBody(ctx, extractionId, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCompleteExtractionApiV1JobsExtractionIdCompletePostResponse(rsp)
}

func (c *ClientWithResponses) CompleteExtractionApiV1JobsExtractionIdCompletePostWithResponse(ctx context.Context, extractionId openapi_types.UUID, body CompleteExtractionApiV1JobsExtractionIdCompletePostJSONRequestBody, reqEditors ...RequestEditorFn) (*CompleteExtractionApiV1JobsExtractionIdCompletePostResponse, error) {
	rsp, err := c.CompleteExtractionApiV1JobsExtractionIdCompletePost(ctx, extractionId, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCompleteExtractionApiV1JobsExtractionIdCompletePostResponse(rsp)
}

// FailExtractionApiV1JobsExtractionIdFailPostWithBodyWithResponse request with arbitrary body returning *FailExtractionApiV1JobsExtractionIdFailPostResponse
func (c *ClientWithResponses) FailExtractionApiV1JobsExtractionIdFailPostWithBodyWithResponse(ctx context.Context, extractionId openapi_types.UUID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*FailExtractionApiV1JobsExtractionIdFailPostResponse, error) {
	rsp, err := c.FailExtractionApiV1JobsExtractionIdFailPostWithBody(ctx, extractionId, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseFailExtractionApiV1JobsExtractionIdFailPostResponse(rsp)
}

func (c *ClientWithResponses) FailExtractionApiV1JobsExtractionIdFailPostWithResponse(ctx context.Context, extractionId openapi_types.UUID, body FailExtractionApiV1JobsExtractionIdFailPostJSONRequestBody, reqEditors ...RequestEditorFn) (*FailExtractionApiV1JobsExtractionIdFailPostResponse, error) {
	rsp, err := c.FailExtractionApiV1JobsExtractionIdFailPost(ctx, extractionId, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseFailExtractionApiV1JobsExtractionIdFailPostResponse(rsp)
}

// HeartbeatExtractionApiV1JobsExtractionIdHeartbeatPostWithResponse request returning *HeartbeatExtractionApiV1JobsExtractionIdHeartbeatPostResponse
func (c *ClientWithResponses) HeartbeatExtractionApiV1JobsExtractionIdHeartbeatPostWithResponse(ctx context.Context, extractionId openapi_types.UUID, params *HeartbeatExtractionApiV1JobsExtractionIdHeartbeatPostParams, reqEditors ...RequestEditorFn) (*HeartbeatExtractionApiV1JobsExtractionIdHeartbeatPostResponse, error) {
	rsp, err := c.HeartbeatExtractionApiV1JobsExtractionIdHeartbeatPost(ctx, extractionId, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseHeartbeatExtractionApiV1JobsExtractionIdHeartbeatPostResponse(rsp)
}

// HealthCheckApiV1SystemHealthGetWithResponse request returning *HealthCheckApiV1SystemHealthGetResponse
func (c *ClientWithResponses) HealthCheckApiV1SystemHealthGetWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*HealthCheckApiV1SystemHealthGetResponse, error) {
	rsp, err := c.HealthCheckApiV1SystemHealthGet(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseHealthCheckApiV1SystemHealthGetResponse(rsp)
}

// PostJobsRegisterWithResponse POST /api/v1/jobs/register com body N-file manifest.
func (c *ClientWithResponses) PostJobsRegisterWithResponse(ctx context.Context, body JobRegisterRequest, reqEditors ...RequestEditorFn) (*PostJobsRegisterResponse, error) {
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	rsp, err := c.RegisterExtractionApiV1JobsRegisterPostWithBody(ctx, "application/json", bytes.NewReader(buf), reqEditors...)
	if err != nil {
		return nil, err
	}
	defer func() { _ = rsp.Body.Close() }()
	bodyBytes, err := io.ReadAll(rsp.Body)
	if err != nil {
		return nil, err
	}
	out := &PostJobsRegisterResponse{Body: bodyBytes, HTTPResponse: rsp}
	if strings.Contains(rsp.Header.Get("Content-Type"), "json") {
		switch rsp.StatusCode {
		case 200:
			var dest JobRegisterResponse
			if err := json.Unmarshal(bodyBytes, &dest); err != nil {
				return nil, err
			}
			out.JSON200 = &dest
		case 422:
			var dest HTTPValidationError
			if err := json.Unmarshal(bodyBytes, &dest); err != nil {
				return nil, err
			}
			out.JSON422 = &dest
		}
	}
	return out, nil
}

// ParseReapLeasesApiV1AdminReapLeasesPostResponse parses an HTTP response from a ReapLeasesApiV1AdminReapLeasesPostWithResponse call
func ParseReapLeasesApiV1AdminReapLeasesPostResponse(rsp *http.Response) (*ReapLeasesApiV1AdminReapLeasesPostResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ReapLeasesApiV1AdminReapLeasesPostResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest map[string]interface{}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseGetAgentStatusApiV1AgentsStatusGetResponse parses an HTTP response from a GetAgentStatusApiV1AgentsStatusGetWithResponse call
func ParseGetAgentStatusApiV1AgentsStatusGetResponse(rsp *http.Response) (*GetAgentStatusApiV1AgentsStatusGetResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetAgentStatusApiV1AgentsStatusGetResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest AgentStatusResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 422:
		var dest HTTPValidationError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON422 = &dest

	}

	return response, nil
}

// ParseNextExtractionApiV1JobsNextGetResponse parses an HTTP response from a NextExtractionApiV1JobsNextGetWithResponse call
func ParseNextExtractionApiV1JobsNextGetResponse(rsp *http.Response) (*NextExtractionApiV1JobsNextGetResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &NextExtractionApiV1JobsNextGetResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest map[string]interface{}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 422:
		var dest HTTPValidationError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON422 = &dest

	}

	return response, nil
}

// ParseRegisterExtractionApiV1JobsRegisterPostResponse parses an HTTP response from a RegisterExtractionApiV1JobsRegisterPostWithResponse call
func ParseRegisterExtractionApiV1JobsRegisterPostResponse(rsp *http.Response) (*RegisterExtractionApiV1JobsRegisterPostResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &RegisterExtractionApiV1JobsRegisterPostResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 201:
		var dest RegisterResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON201 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 422:
		var dest HTTPValidationError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON422 = &dest

	}

	return response, nil
}

// ParseCompleteExtractionApiV1JobsExtractionIdCompletePostResponse parses an HTTP response from a CompleteExtractionApiV1JobsExtractionIdCompletePostWithResponse call
func ParseCompleteExtractionApiV1JobsExtractionIdCompletePostResponse(rsp *http.Response) (*CompleteExtractionApiV1JobsExtractionIdCompletePostResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &CompleteExtractionApiV1JobsExtractionIdCompletePostResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest map[string]interface{}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 422:
		var dest HTTPValidationError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON422 = &dest

	}

	return response, nil
}

// ParseFailExtractionApiV1JobsExtractionIdFailPostResponse parses an HTTP response from a FailExtractionApiV1JobsExtractionIdFailPostWithResponse call
func ParseFailExtractionApiV1JobsExtractionIdFailPostResponse(rsp *http.Response) (*FailExtractionApiV1JobsExtractionIdFailPostResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &FailExtractionApiV1JobsExtractionIdFailPostResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest map[string]interface{}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 422:
		var dest HTTPValidationError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON422 = &dest

	}

	return response, nil
}

// ParseHeartbeatExtractionApiV1JobsExtractionIdHeartbeatPostResponse parses an HTTP response from a HeartbeatExtractionApiV1JobsExtractionIdHeartbeatPostWithResponse call
func ParseHeartbeatExtractionApiV1JobsExtractionIdHeartbeatPostResponse(rsp *http.Response) (*HeartbeatExtractionApiV1JobsExtractionIdHeartbeatPostResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &HeartbeatExtractionApiV1JobsExtractionIdHeartbeatPostResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest map[string]interface{}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 422:
		var dest HTTPValidationError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON422 = &dest

	}

	return response, nil
}

// ParseHealthCheckApiV1SystemHealthGetResponse parses an HTTP response from a HealthCheckApiV1SystemHealthGetWithResponse call
func ParseHealthCheckApiV1SystemHealthGetResponse(rsp *http.Response) (*HealthCheckApiV1SystemHealthGetResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &HealthCheckApiV1SystemHealthGetResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest HealthResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}
