// Package apiclient provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package apiclient

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"
	"time"

	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for ExtractionIntent.
const (
	Equipes          ExtractionIntent = "equipes"
	Estabelecimentos ExtractionIntent = "estabelecimentos"
	Profissionais    ExtractionIntent = "profissionais"
	SihdProducao     ExtractionIntent = "sihd_producao"
)

// AcquireJobRequest defines model for AcquireJobRequest.
type AcquireJobRequest struct {
	MachineId    string  `json:"machine_id"`
	SourceSystem *string `json:"source_system"`
}

// CompleteUploadRequest defines model for CompleteUploadRequest.
type CompleteUploadRequest struct {
	MachineId string `json:"machine_id"`
	ObjectKey string `json:"object_key"`
	SizeBytes int    `json:"size_bytes"`
}

// ExtractionIntent defines model for ExtractionIntent.
type ExtractionIntent string

// ExtractionParams Payload validado para jobs de extração.
type ExtractionParams struct {
	CodMunicipio string           `json:"cod_municipio"`
	Competencia  string           `json:"competencia"`
	Intent       ExtractionIntent `json:"intent"`
}

// HTTPValidationError defines model for HTTPValidationError.
type HTTPValidationError struct {
	Detail *[]ValidationError `json:"detail,omitempty"`
}

// HealthResponse defines model for HealthResponse.
type HealthResponse struct {
	DbConnected bool      `json:"db_connected"`
	Status      string    `json:"status"`
	Timestamp   time.Time `json:"timestamp"`
}

// HeartbeatRequest defines model for HeartbeatRequest.
type HeartbeatRequest struct {
	MachineId string `json:"machine_id"`
}

// HeartbeatResponse defines model for HeartbeatResponse.
type HeartbeatResponse struct {
	LeaseExpiresAt *time.Time `json:"lease_expires_at"`
	Renewed        bool       `json:"renewed"`
}

// JobStatusResponse defines model for JobStatusResponse.
type JobStatusResponse struct {
	CompletedAt  *string `json:"completed_at"`
	CreatedAt    *string `json:"created_at"`
	ErrorDetail  *string `json:"error_detail"`
	JobId        string  `json:"job_id"`
	SourceSystem string  `json:"source_system"`
	StartedAt    *string `json:"started_at"`
	Status       string  `json:"status"`
	TenantId     string  `json:"tenant_id"`
}

// ValidationError defines model for ValidationError.
type ValidationError struct {
	Ctx   *map[string]interface{}    `json:"ctx,omitempty"`
	Input *interface{}               `json:"input,omitempty"`
	Loc   []ValidationError_Loc_Item `json:"loc"`
	Msg   string                     `json:"msg"`
	Type  string                     `json:"type"`
}

// ValidationErrorLoc0 defines model for .
type ValidationErrorLoc0 = string

// ValidationErrorLoc1 defines model for .
type ValidationErrorLoc1 = int

// ValidationError_Loc_Item defines model for ValidationError.loc.Item.
type ValidationError_Loc_Item struct {
	union json.RawMessage
}

// AcquireJobApiV1JobsAcquirePostJSONRequestBody defines body for AcquireJobApiV1JobsAcquirePost for application/json ContentType.
type AcquireJobApiV1JobsAcquirePostJSONRequestBody = AcquireJobRequest

// CreateExtractionJobApiV1JobsCreatePostJSONRequestBody defines body for CreateExtractionJobApiV1JobsCreatePost for application/json ContentType.
type CreateExtractionJobApiV1JobsCreatePostJSONRequestBody = ExtractionParams

// CompleteUploadRouteApiV1JobsJobIdCompleteUploadPostJSONRequestBody defines body for CompleteUploadRouteApiV1JobsJobIdCompleteUploadPost for application/json ContentType.
type CompleteUploadRouteApiV1JobsJobIdCompleteUploadPostJSONRequestBody = CompleteUploadRequest

// HeartbeatApiV1JobsJobIdHeartbeatPostJSONRequestBody defines body for HeartbeatApiV1JobsJobIdHeartbeatPost for application/json ContentType.
type HeartbeatApiV1JobsJobIdHeartbeatPostJSONRequestBody = HeartbeatRequest

// StartStreamingApiV1JobsJobIdStreamingPostJSONRequestBody defines body for StartStreamingApiV1JobsJobIdStreamingPost for application/json ContentType.
type StartStreamingApiV1JobsJobIdStreamingPostJSONRequestBody = HeartbeatRequest

// AsValidationErrorLoc0 returns the union data inside the ValidationError_Loc_Item as a ValidationErrorLoc0
func (t ValidationError_Loc_Item) AsValidationErrorLoc0() (ValidationErrorLoc0, error) {
	var body ValidationErrorLoc0
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromValidationErrorLoc0 overwrites any union data inside the ValidationError_Loc_Item as the provided ValidationErrorLoc0
func (t *ValidationError_Loc_Item) FromValidationErrorLoc0(v ValidationErrorLoc0) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeValidationErrorLoc0 performs a merge with any union data inside the ValidationError_Loc_Item, using the provided ValidationErrorLoc0
func (t *ValidationError_Loc_Item) MergeValidationErrorLoc0(v ValidationErrorLoc0) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsValidationErrorLoc1 returns the union data inside the ValidationError_Loc_Item as a ValidationErrorLoc1
func (t ValidationError_Loc_Item) AsValidationErrorLoc1() (ValidationErrorLoc1, error) {
	var body ValidationErrorLoc1
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromValidationErrorLoc1 overwrites any union data inside the ValidationError_Loc_Item as the provided ValidationErrorLoc1
func (t *ValidationError_Loc_Item) FromValidationErrorLoc1(v ValidationErrorLoc1) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeValidationErrorLoc1 performs a merge with any union data inside the ValidationError_Loc_Item, using the provided ValidationErrorLoc1
func (t *ValidationError_Loc_Item) MergeValidationErrorLoc1(v ValidationErrorLoc1) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t ValidationError_Loc_Item) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *ValidationError_Loc_Item) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// ReapLeasesApiV1AdminReapLeasesPost request
	ReapLeasesApiV1AdminReapLeasesPost(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// AcquireJobApiV1JobsAcquirePostWithBody request with any body
	AcquireJobApiV1JobsAcquirePostWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	AcquireJobApiV1JobsAcquirePost(ctx context.Context, body AcquireJobApiV1JobsAcquirePostJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// CreateExtractionJobApiV1JobsCreatePostWithBody request with any body
	CreateExtractionJobApiV1JobsCreatePostWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	CreateExtractionJobApiV1JobsCreatePost(ctx context.Context, body CreateExtractionJobApiV1JobsCreatePostJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetJobStatusApiV1JobsJobIdGet request
	GetJobStatusApiV1JobsJobIdGet(ctx context.Context, jobId string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// CompleteUploadRouteApiV1JobsJobIdCompleteUploadPostWithBody request with any body
	CompleteUploadRouteApiV1JobsJobIdCompleteUploadPostWithBody(ctx context.Context, jobId openapi_types.UUID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	CompleteUploadRouteApiV1JobsJobIdCompleteUploadPost(ctx context.Context, jobId openapi_types.UUID, body CompleteUploadRouteApiV1JobsJobIdCompleteUploadPostJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// HeartbeatApiV1JobsJobIdHeartbeatPostWithBody request with any body
	HeartbeatApiV1JobsJobIdHeartbeatPostWithBody(ctx context.Context, jobId openapi_types.UUID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	HeartbeatApiV1JobsJobIdHeartbeatPost(ctx context.Context, jobId openapi_types.UUID, body HeartbeatApiV1JobsJobIdHeartbeatPostJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// StartStreamingApiV1JobsJobIdStreamingPostWithBody request with any body
	StartStreamingApiV1JobsJobIdStreamingPostWithBody(ctx context.Context, jobId openapi_types.UUID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	StartStreamingApiV1JobsJobIdStreamingPost(ctx context.Context, jobId openapi_types.UUID, body StartStreamingApiV1JobsJobIdStreamingPostJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// HealthCheckApiV1SystemHealthGet request
	HealthCheckApiV1SystemHealthGet(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) ReapLeasesApiV1AdminReapLeasesPost(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewReapLeasesApiV1AdminReapLeasesPostRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) AcquireJobApiV1JobsAcquirePostWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewAcquireJobApiV1JobsAcquirePostRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) AcquireJobApiV1JobsAcquirePost(ctx context.Context, body AcquireJobApiV1JobsAcquirePostJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewAcquireJobApiV1JobsAcquirePostRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CreateExtractionJobApiV1JobsCreatePostWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateExtractionJobApiV1JobsCreatePostRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CreateExtractionJobApiV1JobsCreatePost(ctx context.Context, body CreateExtractionJobApiV1JobsCreatePostJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateExtractionJobApiV1JobsCreatePostRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetJobStatusApiV1JobsJobIdGet(ctx context.Context, jobId string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetJobStatusApiV1JobsJobIdGetRequest(c.Server, jobId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CompleteUploadRouteApiV1JobsJobIdCompleteUploadPostWithBody(ctx context.Context, jobId openapi_types.UUID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCompleteUploadRouteApiV1JobsJobIdCompleteUploadPostRequestWithBody(c.Server, jobId, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CompleteUploadRouteApiV1JobsJobIdCompleteUploadPost(ctx context.Context, jobId openapi_types.UUID, body CompleteUploadRouteApiV1JobsJobIdCompleteUploadPostJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCompleteUploadRouteApiV1JobsJobIdCompleteUploadPostRequest(c.Server, jobId, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) HeartbeatApiV1JobsJobIdHeartbeatPostWithBody(ctx context.Context, jobId openapi_types.UUID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewHeartbeatApiV1JobsJobIdHeartbeatPostRequestWithBody(c.Server, jobId, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) HeartbeatApiV1JobsJobIdHeartbeatPost(ctx context.Context, jobId openapi_types.UUID, body HeartbeatApiV1JobsJobIdHeartbeatPostJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewHeartbeatApiV1JobsJobIdHeartbeatPostRequest(c.Server, jobId, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) StartStreamingApiV1JobsJobIdStreamingPostWithBody(ctx context.Context, jobId openapi_types.UUID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewStartStreamingApiV1JobsJobIdStreamingPostRequestWithBody(c.Server, jobId, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) StartStreamingApiV1JobsJobIdStreamingPost(ctx context.Context, jobId openapi_types.UUID, body StartStreamingApiV1JobsJobIdStreamingPostJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewStartStreamingApiV1JobsJobIdStreamingPostRequest(c.Server, jobId, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) HealthCheckApiV1SystemHealthGet(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewHealthCheckApiV1SystemHealthGetRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewReapLeasesApiV1AdminReapLeasesPostRequest generates requests for ReapLeasesApiV1AdminReapLeasesPost
func NewReapLeasesApiV1AdminReapLeasesPostRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/admin/reap-leases")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewAcquireJobApiV1JobsAcquirePostRequest calls the generic AcquireJobApiV1JobsAcquirePost builder with application/json body
func NewAcquireJobApiV1JobsAcquirePostRequest(server string, body AcquireJobApiV1JobsAcquirePostJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewAcquireJobApiV1JobsAcquirePostRequestWithBody(server, "application/json", bodyReader)
}

// NewAcquireJobApiV1JobsAcquirePostRequestWithBody generates requests for AcquireJobApiV1JobsAcquirePost with any type of body
func NewAcquireJobApiV1JobsAcquirePostRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/jobs/acquire")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewCreateExtractionJobApiV1JobsCreatePostRequest calls the generic CreateExtractionJobApiV1JobsCreatePost builder with application/json body
func NewCreateExtractionJobApiV1JobsCreatePostRequest(server string, body CreateExtractionJobApiV1JobsCreatePostJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewCreateExtractionJobApiV1JobsCreatePostRequestWithBody(server, "application/json", bodyReader)
}

// NewCreateExtractionJobApiV1JobsCreatePostRequestWithBody generates requests for CreateExtractionJobApiV1JobsCreatePost with any type of body
func NewCreateExtractionJobApiV1JobsCreatePostRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/jobs/create")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewGetJobStatusApiV1JobsJobIdGetRequest generates requests for GetJobStatusApiV1JobsJobIdGet
func NewGetJobStatusApiV1JobsJobIdGetRequest(server string, jobId string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "job_id", runtime.ParamLocationPath, jobId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/jobs/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewCompleteUploadRouteApiV1JobsJobIdCompleteUploadPostRequest calls the generic CompleteUploadRouteApiV1JobsJobIdCompleteUploadPost builder with application/json body
func NewCompleteUploadRouteApiV1JobsJobIdCompleteUploadPostRequest(server string, jobId openapi_types.UUID, body CompleteUploadRouteApiV1JobsJobIdCompleteUploadPostJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewCompleteUploadRouteApiV1JobsJobIdCompleteUploadPostRequestWithBody(server, jobId, "application/json", bodyReader)
}

// NewCompleteUploadRouteApiV1JobsJobIdCompleteUploadPostRequestWithBody generates requests for CompleteUploadRouteApiV1JobsJobIdCompleteUploadPost with any type of body
func NewCompleteUploadRouteApiV1JobsJobIdCompleteUploadPostRequestWithBody(server string, jobId openapi_types.UUID, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "job_id", runtime.ParamLocationPath, jobId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/jobs/%s/complete-upload", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewHeartbeatApiV1JobsJobIdHeartbeatPostRequest calls the generic HeartbeatApiV1JobsJobIdHeartbeatPost builder with application/json body
func NewHeartbeatApiV1JobsJobIdHeartbeatPostRequest(server string, jobId openapi_types.UUID, body HeartbeatApiV1JobsJobIdHeartbeatPostJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewHeartbeatApiV1JobsJobIdHeartbeatPostRequestWithBody(server, jobId, "application/json", bodyReader)
}

// NewHeartbeatApiV1JobsJobIdHeartbeatPostRequestWithBody generates requests for HeartbeatApiV1JobsJobIdHeartbeatPost with any type of body
func NewHeartbeatApiV1JobsJobIdHeartbeatPostRequestWithBody(server string, jobId openapi_types.UUID, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "job_id", runtime.ParamLocationPath, jobId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/jobs/%s/heartbeat", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewStartStreamingApiV1JobsJobIdStreamingPostRequest calls the generic StartStreamingApiV1JobsJobIdStreamingPost builder with application/json body
func NewStartStreamingApiV1JobsJobIdStreamingPostRequest(server string, jobId openapi_types.UUID, body StartStreamingApiV1JobsJobIdStreamingPostJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewStartStreamingApiV1JobsJobIdStreamingPostRequestWithBody(server, jobId, "application/json", bodyReader)
}

// NewStartStreamingApiV1JobsJobIdStreamingPostRequestWithBody generates requests for StartStreamingApiV1JobsJobIdStreamingPost with any type of body
func NewStartStreamingApiV1JobsJobIdStreamingPostRequestWithBody(server string, jobId openapi_types.UUID, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "job_id", runtime.ParamLocationPath, jobId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/jobs/%s/streaming", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewHealthCheckApiV1SystemHealthGetRequest generates requests for HealthCheckApiV1SystemHealthGet
func NewHealthCheckApiV1SystemHealthGetRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/system/health")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// ReapLeasesApiV1AdminReapLeasesPostWithResponse request
	ReapLeasesApiV1AdminReapLeasesPostWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*ReapLeasesApiV1AdminReapLeasesPostResponse, error)

	// AcquireJobApiV1JobsAcquirePostWithBodyWithResponse request with any body
	AcquireJobApiV1JobsAcquirePostWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*AcquireJobApiV1JobsAcquirePostResponse, error)

	AcquireJobApiV1JobsAcquirePostWithResponse(ctx context.Context, body AcquireJobApiV1JobsAcquirePostJSONRequestBody, reqEditors ...RequestEditorFn) (*AcquireJobApiV1JobsAcquirePostResponse, error)

	// CreateExtractionJobApiV1JobsCreatePostWithBodyWithResponse request with any body
	CreateExtractionJobApiV1JobsCreatePostWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateExtractionJobApiV1JobsCreatePostResponse, error)

	CreateExtractionJobApiV1JobsCreatePostWithResponse(ctx context.Context, body CreateExtractionJobApiV1JobsCreatePostJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateExtractionJobApiV1JobsCreatePostResponse, error)

	// GetJobStatusApiV1JobsJobIdGetWithResponse request
	GetJobStatusApiV1JobsJobIdGetWithResponse(ctx context.Context, jobId string, reqEditors ...RequestEditorFn) (*GetJobStatusApiV1JobsJobIdGetResponse, error)

	// CompleteUploadRouteApiV1JobsJobIdCompleteUploadPostWithBodyWithResponse request with any body
	CompleteUploadRouteApiV1JobsJobIdCompleteUploadPostWithBodyWithResponse(ctx context.Context, jobId openapi_types.UUID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CompleteUploadRouteApiV1JobsJobIdCompleteUploadPostResponse, error)

	CompleteUploadRouteApiV1JobsJobIdCompleteUploadPostWithResponse(ctx context.Context, jobId openapi_types.UUID, body CompleteUploadRouteApiV1JobsJobIdCompleteUploadPostJSONRequestBody, reqEditors ...RequestEditorFn) (*CompleteUploadRouteApiV1JobsJobIdCompleteUploadPostResponse, error)

	// HeartbeatApiV1JobsJobIdHeartbeatPostWithBodyWithResponse request with any body
	HeartbeatApiV1JobsJobIdHeartbeatPostWithBodyWithResponse(ctx context.Context, jobId openapi_types.UUID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*HeartbeatApiV1JobsJobIdHeartbeatPostResponse, error)

	HeartbeatApiV1JobsJobIdHeartbeatPostWithResponse(ctx context.Context, jobId openapi_types.UUID, body HeartbeatApiV1JobsJobIdHeartbeatPostJSONRequestBody, reqEditors ...RequestEditorFn) (*HeartbeatApiV1JobsJobIdHeartbeatPostResponse, error)

	// StartStreamingApiV1JobsJobIdStreamingPostWithBodyWithResponse request with any body
	StartStreamingApiV1JobsJobIdStreamingPostWithBodyWithResponse(ctx context.Context, jobId openapi_types.UUID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*StartStreamingApiV1JobsJobIdStreamingPostResponse, error)

	StartStreamingApiV1JobsJobIdStreamingPostWithResponse(ctx context.Context, jobId openapi_types.UUID, body StartStreamingApiV1JobsJobIdStreamingPostJSONRequestBody, reqEditors ...RequestEditorFn) (*StartStreamingApiV1JobsJobIdStreamingPostResponse, error)

	// HealthCheckApiV1SystemHealthGetWithResponse request
	HealthCheckApiV1SystemHealthGetWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*HealthCheckApiV1SystemHealthGetResponse, error)
}

type ReapLeasesApiV1AdminReapLeasesPostResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *map[string]interface{}
}

// Status returns HTTPResponse.Status
func (r ReapLeasesApiV1AdminReapLeasesPostResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ReapLeasesApiV1AdminReapLeasesPostResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type AcquireJobApiV1JobsAcquirePostResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *interface{}
	JSON422      *HTTPValidationError
}

// Status returns HTTPResponse.Status
func (r AcquireJobApiV1JobsAcquirePostResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r AcquireJobApiV1JobsAcquirePostResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type CreateExtractionJobApiV1JobsCreatePostResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON201      *map[string]interface{}
	JSON422      *HTTPValidationError
}

// Status returns HTTPResponse.Status
func (r CreateExtractionJobApiV1JobsCreatePostResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r CreateExtractionJobApiV1JobsCreatePostResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetJobStatusApiV1JobsJobIdGetResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *JobStatusResponse
	JSON422      *HTTPValidationError
}

// Status returns HTTPResponse.Status
func (r GetJobStatusApiV1JobsJobIdGetResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetJobStatusApiV1JobsJobIdGetResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type CompleteUploadRouteApiV1JobsJobIdCompleteUploadPostResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *interface{}
	JSON422      *HTTPValidationError
}

// Status returns HTTPResponse.Status
func (r CompleteUploadRouteApiV1JobsJobIdCompleteUploadPostResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r CompleteUploadRouteApiV1JobsJobIdCompleteUploadPostResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type HeartbeatApiV1JobsJobIdHeartbeatPostResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *HeartbeatResponse
	JSON422      *HTTPValidationError
}

// Status returns HTTPResponse.Status
func (r HeartbeatApiV1JobsJobIdHeartbeatPostResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r HeartbeatApiV1JobsJobIdHeartbeatPostResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type StartStreamingApiV1JobsJobIdStreamingPostResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *interface{}
	JSON422      *HTTPValidationError
}

// Status returns HTTPResponse.Status
func (r StartStreamingApiV1JobsJobIdStreamingPostResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r StartStreamingApiV1JobsJobIdStreamingPostResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type HealthCheckApiV1SystemHealthGetResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *HealthResponse
}

// Status returns HTTPResponse.Status
func (r HealthCheckApiV1SystemHealthGetResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r HealthCheckApiV1SystemHealthGetResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ReapLeasesApiV1AdminReapLeasesPostWithResponse request returning *ReapLeasesApiV1AdminReapLeasesPostResponse
func (c *ClientWithResponses) ReapLeasesApiV1AdminReapLeasesPostWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*ReapLeasesApiV1AdminReapLeasesPostResponse, error) {
	rsp, err := c.ReapLeasesApiV1AdminReapLeasesPost(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseReapLeasesApiV1AdminReapLeasesPostResponse(rsp)
}

// AcquireJobApiV1JobsAcquirePostWithBodyWithResponse request with arbitrary body returning *AcquireJobApiV1JobsAcquirePostResponse
func (c *ClientWithResponses) AcquireJobApiV1JobsAcquirePostWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*AcquireJobApiV1JobsAcquirePostResponse, error) {
	rsp, err := c.AcquireJobApiV1JobsAcquirePostWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseAcquireJobApiV1JobsAcquirePostResponse(rsp)
}

func (c *ClientWithResponses) AcquireJobApiV1JobsAcquirePostWithResponse(ctx context.Context, body AcquireJobApiV1JobsAcquirePostJSONRequestBody, reqEditors ...RequestEditorFn) (*AcquireJobApiV1JobsAcquirePostResponse, error) {
	rsp, err := c.AcquireJobApiV1JobsAcquirePost(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseAcquireJobApiV1JobsAcquirePostResponse(rsp)
}

// CreateExtractionJobApiV1JobsCreatePostWithBodyWithResponse request with arbitrary body returning *CreateExtractionJobApiV1JobsCreatePostResponse
func (c *ClientWithResponses) CreateExtractionJobApiV1JobsCreatePostWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateExtractionJobApiV1JobsCreatePostResponse, error) {
	rsp, err := c.CreateExtractionJobApiV1JobsCreatePostWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateExtractionJobApiV1JobsCreatePostResponse(rsp)
}

func (c *ClientWithResponses) CreateExtractionJobApiV1JobsCreatePostWithResponse(ctx context.Context, body CreateExtractionJobApiV1JobsCreatePostJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateExtractionJobApiV1JobsCreatePostResponse, error) {
	rsp, err := c.CreateExtractionJobApiV1JobsCreatePost(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateExtractionJobApiV1JobsCreatePostResponse(rsp)
}

// GetJobStatusApiV1JobsJobIdGetWithResponse request returning *GetJobStatusApiV1JobsJobIdGetResponse
func (c *ClientWithResponses) GetJobStatusApiV1JobsJobIdGetWithResponse(ctx context.Context, jobId string, reqEditors ...RequestEditorFn) (*GetJobStatusApiV1JobsJobIdGetResponse, error) {
	rsp, err := c.GetJobStatusApiV1JobsJobIdGet(ctx, jobId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetJobStatusApiV1JobsJobIdGetResponse(rsp)
}

// CompleteUploadRouteApiV1JobsJobIdCompleteUploadPostWithBodyWithResponse request with arbitrary body returning *CompleteUploadRouteApiV1JobsJobIdCompleteUploadPostResponse
func (c *ClientWithResponses) CompleteUploadRouteApiV1JobsJobIdCompleteUploadPostWithBodyWithResponse(ctx context.Context, jobId openapi_types.UUID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CompleteUploadRouteApiV1JobsJobIdCompleteUploadPostResponse, error) {
	rsp, err := c.CompleteUploadRouteApiV1JobsJobIdCompleteUploadPostWithBody(ctx, jobId, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCompleteUploadRouteApiV1JobsJobIdCompleteUploadPostResponse(rsp)
}

func (c *ClientWithResponses) CompleteUploadRouteApiV1JobsJobIdCompleteUploadPostWithResponse(ctx context.Context, jobId openapi_types.UUID, body CompleteUploadRouteApiV1JobsJobIdCompleteUploadPostJSONRequestBody, reqEditors ...RequestEditorFn) (*CompleteUploadRouteApiV1JobsJobIdCompleteUploadPostResponse, error) {
	rsp, err := c.CompleteUploadRouteApiV1JobsJobIdCompleteUploadPost(ctx, jobId, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCompleteUploadRouteApiV1JobsJobIdCompleteUploadPostResponse(rsp)
}

// HeartbeatApiV1JobsJobIdHeartbeatPostWithBodyWithResponse request with arbitrary body returning *HeartbeatApiV1JobsJobIdHeartbeatPostResponse
func (c *ClientWithResponses) HeartbeatApiV1JobsJobIdHeartbeatPostWithBodyWithResponse(ctx context.Context, jobId openapi_types.UUID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*HeartbeatApiV1JobsJobIdHeartbeatPostResponse, error) {
	rsp, err := c.HeartbeatApiV1JobsJobIdHeartbeatPostWithBody(ctx, jobId, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseHeartbeatApiV1JobsJobIdHeartbeatPostResponse(rsp)
}

func (c *ClientWithResponses) HeartbeatApiV1JobsJobIdHeartbeatPostWithResponse(ctx context.Context, jobId openapi_types.UUID, body HeartbeatApiV1JobsJobIdHeartbeatPostJSONRequestBody, reqEditors ...RequestEditorFn) (*HeartbeatApiV1JobsJobIdHeartbeatPostResponse, error) {
	rsp, err := c.HeartbeatApiV1JobsJobIdHeartbeatPost(ctx, jobId, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseHeartbeatApiV1JobsJobIdHeartbeatPostResponse(rsp)
}

// StartStreamingApiV1JobsJobIdStreamingPostWithBodyWithResponse request with arbitrary body returning *StartStreamingApiV1JobsJobIdStreamingPostResponse
func (c *ClientWithResponses) StartStreamingApiV1JobsJobIdStreamingPostWithBodyWithResponse(ctx context.Context, jobId openapi_types.UUID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*StartStreamingApiV1JobsJobIdStreamingPostResponse, error) {
	rsp, err := c.StartStreamingApiV1JobsJobIdStreamingPostWithBody(ctx, jobId, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseStartStreamingApiV1JobsJobIdStreamingPostResponse(rsp)
}

func (c *ClientWithResponses) StartStreamingApiV1JobsJobIdStreamingPostWithResponse(ctx context.Context, jobId openapi_types.UUID, body StartStreamingApiV1JobsJobIdStreamingPostJSONRequestBody, reqEditors ...RequestEditorFn) (*StartStreamingApiV1JobsJobIdStreamingPostResponse, error) {
	rsp, err := c.StartStreamingApiV1JobsJobIdStreamingPost(ctx, jobId, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseStartStreamingApiV1JobsJobIdStreamingPostResponse(rsp)
}

// HealthCheckApiV1SystemHealthGetWithResponse request returning *HealthCheckApiV1SystemHealthGetResponse
func (c *ClientWithResponses) HealthCheckApiV1SystemHealthGetWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*HealthCheckApiV1SystemHealthGetResponse, error) {
	rsp, err := c.HealthCheckApiV1SystemHealthGet(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseHealthCheckApiV1SystemHealthGetResponse(rsp)
}

// ParseReapLeasesApiV1AdminReapLeasesPostResponse parses an HTTP response from a ReapLeasesApiV1AdminReapLeasesPostWithResponse call
func ParseReapLeasesApiV1AdminReapLeasesPostResponse(rsp *http.Response) (*ReapLeasesApiV1AdminReapLeasesPostResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ReapLeasesApiV1AdminReapLeasesPostResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest map[string]interface{}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseAcquireJobApiV1JobsAcquirePostResponse parses an HTTP response from a AcquireJobApiV1JobsAcquirePostWithResponse call
func ParseAcquireJobApiV1JobsAcquirePostResponse(rsp *http.Response) (*AcquireJobApiV1JobsAcquirePostResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &AcquireJobApiV1JobsAcquirePostResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest interface{}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 422:
		var dest HTTPValidationError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON422 = &dest

	}

	return response, nil
}

// ParseCreateExtractionJobApiV1JobsCreatePostResponse parses an HTTP response from a CreateExtractionJobApiV1JobsCreatePostWithResponse call
func ParseCreateExtractionJobApiV1JobsCreatePostResponse(rsp *http.Response) (*CreateExtractionJobApiV1JobsCreatePostResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &CreateExtractionJobApiV1JobsCreatePostResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 201:
		var dest map[string]interface{}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON201 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 422:
		var dest HTTPValidationError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON422 = &dest

	}

	return response, nil
}

// ParseGetJobStatusApiV1JobsJobIdGetResponse parses an HTTP response from a GetJobStatusApiV1JobsJobIdGetWithResponse call
func ParseGetJobStatusApiV1JobsJobIdGetResponse(rsp *http.Response) (*GetJobStatusApiV1JobsJobIdGetResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetJobStatusApiV1JobsJobIdGetResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest JobStatusResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 422:
		var dest HTTPValidationError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON422 = &dest

	}

	return response, nil
}

// ParseCompleteUploadRouteApiV1JobsJobIdCompleteUploadPostResponse parses an HTTP response from a CompleteUploadRouteApiV1JobsJobIdCompleteUploadPostWithResponse call
func ParseCompleteUploadRouteApiV1JobsJobIdCompleteUploadPostResponse(rsp *http.Response) (*CompleteUploadRouteApiV1JobsJobIdCompleteUploadPostResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &CompleteUploadRouteApiV1JobsJobIdCompleteUploadPostResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest interface{}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 422:
		var dest HTTPValidationError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON422 = &dest

	}

	return response, nil
}

// ParseHeartbeatApiV1JobsJobIdHeartbeatPostResponse parses an HTTP response from a HeartbeatApiV1JobsJobIdHeartbeatPostWithResponse call
func ParseHeartbeatApiV1JobsJobIdHeartbeatPostResponse(rsp *http.Response) (*HeartbeatApiV1JobsJobIdHeartbeatPostResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &HeartbeatApiV1JobsJobIdHeartbeatPostResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest HeartbeatResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 422:
		var dest HTTPValidationError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON422 = &dest

	}

	return response, nil
}

// ParseStartStreamingApiV1JobsJobIdStreamingPostResponse parses an HTTP response from a StartStreamingApiV1JobsJobIdStreamingPostWithResponse call
func ParseStartStreamingApiV1JobsJobIdStreamingPostResponse(rsp *http.Response) (*StartStreamingApiV1JobsJobIdStreamingPostResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &StartStreamingApiV1JobsJobIdStreamingPostResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest interface{}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 422:
		var dest HTTPValidationError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON422 = &dest

	}

	return response, nil
}

// ParseHealthCheckApiV1SystemHealthGetResponse parses an HTTP response from a HealthCheckApiV1SystemHealthGetWithResponse call
func ParseHealthCheckApiV1SystemHealthGetResponse(rsp *http.Response) (*HealthCheckApiV1SystemHealthGetResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &HealthCheckApiV1SystemHealthGetResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest HealthResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}
