"""Canonical control-plane states."""

from enum import StrEnum


class JobState(StrEnum):
    PENDING = "PENDING"
    LEASED = "LEASED"
    SUCCEEDED = "SUCCEEDED"
    FAILED_RETRYABLE = "FAILED_RETRYABLE"
    FAILED_FINAL = "FAILED_FINAL"
    CANCEL_REQUESTED = "CANCEL_REQUESTED"
    CANCELED = "CANCELED"


class RunState(StrEnum):
    PLANNED = "PLANNED"
    WAITING_INPUTS = "WAITING_INPUTS"
    PROCESSING = "PROCESSING"
    PUBLISHING = "PUBLISHING"
    PUBLISHED = "PUBLISHED"
    PUBLISHED_DEGRADED = "PUBLISHED_DEGRADED"
    FAILED = "FAILED"
    CANCEL_REQUESTED = "CANCEL_REQUESTED"
    CANCELED = "CANCELED"


class RunUnitState(StrEnum):
    PENDING = "PENDING"
    LEASED = "LEASED"
    SUCCEEDED = "SUCCEEDED"
    SUCCEEDED_DEGRADED = "SUCCEEDED_DEGRADED"
    FAILED_RETRYABLE = "FAILED_RETRYABLE"
    FAILED_FINAL = "FAILED_FINAL"
    CANCELED = "CANCELED"


class RunStage(StrEnum):
    NORMALIZE = "NORMALIZE"
    RECONCILE = "RECONCILE"
    MATERIALIZE = "MATERIALIZE"


class DispatchState(StrEnum):
    RESERVED = "RESERVED"
    STARTED = "STARTED"
    TERMINAL = "TERMINAL"


class DispatchOutcome(StrEnum):
    SUCCEEDED = "SUCCEEDED"
    FAILED = "FAILED"
    CANCELED = "CANCELED"


class AgentState(StrEnum):
    ACTIVE = "ACTIVE"
    REVOKED = "REVOKED"


class AccessRequestState(StrEnum):
    PENDING = "PENDING"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
