from collections import OrderedDict
from collections.abc import Callable, Iterator
from os import PathLike
from types import TracebackType
from typing import Any, Self

__all__: list[str]
__version__: str

class InvalidValue(bytes): ...

class DBFField:
    name: str
    type: str
    address: int
    length: int
    decimal_count: int
    def __getattr__(self, name: str) -> Any: ...

class FieldParser:
    table: DBF
    encoding: str
    char_decode_errors: str
    def __init__(self, table: DBF, memofile: Any = None) -> None: ...
    def decode_text(self, text: bytes) -> str: ...
    def field_type_supported(self, field_type: str) -> bool: ...
    def parse(self, field: Any, data: bytes) -> Any: ...
    def parse0(self, field: Any, data: bytes) -> Any: ...
    def parseC(self, field: Any, data: bytes) -> Any: ...
    def parseD(self, field: Any, data: bytes) -> Any: ...
    def parseF(self, field: Any, data: bytes) -> Any: ...
    def parseI(self, field: Any, data: bytes) -> Any: ...
    def parseL(self, field: Any, data: bytes) -> Any: ...
    def parseM(self, field: Any, data: bytes) -> Any: ...
    def parseN(self, field: Any, data: bytes) -> Any: ...
    def parseO(self, field: Any, data: bytes) -> Any: ...
    def parseT(self, field: Any, data: bytes) -> Any: ...
    def parseY(self, field: Any, data: bytes) -> Any: ...
    def __getattr__(self, name: str) -> Any: ...

class DBF:
    filename: str
    encoding: str | None
    ignorecase: bool
    lowernames: bool
    parserclass: type[FieldParser]
    raw: bool
    ignore_missing_memofile: bool
    char_decode_errors: str
    fields: list[DBFField]
    field_names: list[str]
    header: Any
    def __init__(
        self,
        filename: str | PathLike[str],
        encoding: str | None = None,
        ignorecase: bool = True,
        lowernames: bool = False,
        parserclass: type[FieldParser] = ...,
        recfactory: Callable[..., Any] | None = ...,
        load: bool = False,
        raw: bool = False,
        ignore_missing_memofile: bool = False,
        char_decode_errors: str = "strict",
    ) -> None: ...
    @property
    def dbversion(self) -> str: ...
    @property
    def loaded(self) -> bool: ...
    @property
    def records(self) -> Any: ...
    @property
    def deleted(self) -> Any: ...
    def load(self) -> None: ...
    def unload(self) -> None: ...
    def __iter__(self) -> Iterator[OrderedDict[str, Any]]: ...
    def __len__(self) -> int: ...
    def __enter__(self) -> Self: ...
    def __exit__(
        self,
        type: type[BaseException] | None,
        value: BaseException | None,
        traceback: TracebackType | None,
    ) -> None: ...
    def __getattr__(self, name: str) -> Any: ...

def __getattr__(name: str) -> Any: ...
