"""Porta de persistência do plano de controle."""

from __future__ import annotations

from typing import TYPE_CHECKING, Protocol, runtime_checkable

if TYPE_CHECKING:
    from datetime import datetime

    from cnes_domain.control_plane.commands import (
        BeginIdempotency,
        BindRunDispatch,
        CancelJob,
        ClaimJob,
        ClaimRunUnit,
        CommitRunUnit,
        CompleteJob,
        FailJob,
        FailRunUnit,
        FinalizeRunCancellation,
        FinishRunDispatch,
        IdempotencyOutcome,
        PublishDataset,
        PutRunUnits,
        RenewJobLease,
        ReserveRunDispatch,
        TransitionRun,
    )
    from cnes_domain.control_plane.entities import (
        AccessRequest,
        Agent,
        DatasetPointer,
        DatasetVersion,
        Job,
        ManifestRef,
        Membership,
        OutboxEvent,
        Run,
        RunDispatch,
        RunUnit,
        Tenant,
    )
    from cnes_domain.control_plane.queries import (
        LatestSucceededJobQuery,
        RawManifestChainQuery,
        WaitingRunsForDependencyQuery,
    )


@runtime_checkable
class ControlPlanePort(Protocol):
    def get_tenant(self, tenant_id: str) -> Tenant | None: ...
    def put_tenant(self, tenant: Tenant) -> None: ...
    def get_membership(self, tenant_id: str, user_id: str) -> Membership | None: ...
    def put_membership(self, membership: Membership) -> None: ...
    def get_agent(self, tenant_id: str, agent_id: str) -> Agent | None: ...
    def put_agent(self, agent: Agent) -> None: ...
    def create_job(self, job: Job, event: OutboxEvent) -> Job: ...
    def get_job(self, tenant_id: str, job_id: str) -> Job | None: ...
    def latest_succeeded_job(
        self,
        tenant_id: str,
        agent_id: str,
        source_type: str,
        file_subtype: str,
        competencia: str,
    ) -> Job | None: ...
    def list_raw_manifest_chain(
        self,
        tenant_id: str,
        source_type: str,
        file_subtype: str,
        competencia: str,
        limit: int = 31,
    ) -> tuple[ManifestRef, ...]: ...
    def list_claimable_jobs(
        self, tenant_id: str, agent_id: str, limit: int
    ) -> tuple[Job, ...]: ...
    def claim_job(self, command: ClaimJob) -> Job | None: ...
    def renew_job_lease(self, command: RenewJobLease) -> Job: ...
    def complete_job(self, command: CompleteJob, event: OutboxEvent) -> Job: ...
    def fail_job(self, command: FailJob, event: OutboxEvent) -> Job: ...
    def cancel_job(self, command: CancelJob, event: OutboxEvent) -> Job: ...
    def put_run(self, run: Run) -> None: ...
    def get_run(self, tenant_id: str, run_id: str) -> Run | None: ...
    def list_waiting_runs_for_dependency(
        self,
        tenant_id: str,
        source_type: str,
        file_subtype: str,
        competencia: str,
        limit: int = 100,
    ) -> tuple[Run, ...]: ...
    def list_recoverable_runs(
        self, now: datetime, limit: int = 100
    ) -> tuple[Run, ...]: ...
    def transition_run(self, command: TransitionRun, event: OutboxEvent) -> Run: ...
    def put_run_units(self, command: PutRunUnits) -> tuple[RunUnit, ...]: ...
    def list_run_units(self, tenant_id: str, run_id: str) -> tuple[RunUnit, ...]: ...
    def claim_run_unit(self, command: ClaimRunUnit) -> RunUnit | None: ...
    def commit_run_unit(self, command: CommitRunUnit, event: OutboxEvent) -> RunUnit: ...
    def fail_run_unit(self, command: FailRunUnit, event: OutboxEvent) -> RunUnit: ...
    def finalize_run_cancellation(
        self, command: FinalizeRunCancellation, event: OutboxEvent
    ) -> Run: ...
    def reserve_run_dispatch(self, command: ReserveRunDispatch) -> RunDispatch: ...
    def bind_run_dispatch(self, command: BindRunDispatch) -> RunDispatch: ...
    def finish_run_dispatch(self, command: FinishRunDispatch) -> RunDispatch: ...
    def get_active_run_dispatch(self, tenant_id: str, run_id: str) -> RunDispatch | None: ...
    def begin_idempotency(self, command: BeginIdempotency) -> IdempotencyOutcome: ...
    def publish_dataset(self, command: PublishDataset) -> DatasetPointer: ...
    def get_dataset_pointer(
        self, tenant_id: str, dataset_name: str
    ) -> DatasetPointer | None: ...
    def get_dataset_version(
        self, tenant_id: str, dataset_name: str, version_id: str
    ) -> DatasetVersion | None: ...
    def put_access_request(self, request: AccessRequest, event: OutboxEvent) -> None: ...
    def get_access_request(self, tenant_id: str, request_id: str) -> AccessRequest | None: ...
    def decide_access_request(
        self, request: AccessRequest, event: OutboxEvent
    ) -> AccessRequest: ...
    def pending_outbox(self, limit: int) -> tuple[OutboxEvent, ...]: ...
    def mark_outbox_delivered(self, event_id: str, delivered_at: datetime) -> None: ...


@runtime_checkable
class TypedRawQueryPort(Protocol):
    def query_latest_succeeded_job(self, query: LatestSucceededJobQuery) -> Job | None: ...
    def query_raw_manifest_chain(
        self, query: RawManifestChainQuery
    ) -> tuple[ManifestRef, ...]: ...
    def query_waiting_runs_for_dependency(
        self, query: WaitingRunsForDependencyQuery
    ) -> tuple[Run, ...]: ...
